### ISSUE TITLE
As a project manager I would like to shut down the old realtimebus back-end systems, as well as our prototype applications connected to it

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/realtimebus-v2#17]
With the launch of the new OTP implementation, all this system can be definitely shut down. 
As far as the back-end systems are concerned, we should have mainly two back-end systems:
- [x] realtimebus v1 (old system developed for the first version of bus.meran.eu, probably already switched off - please check) - https://github.com/noi-techpark/realtimebus
   > archived and deactivated
- [x] realtimebus v2 (the new system that was developed by Daniel Rampanelli) - https://github.com/noi-techpark/realtimebus-v2
  > archived and deactivated

The front-end applications that were using this back-end where:
- [ ] the application that was previously accessible through the domain mobility.meran.eu - https://github.com/noi-techpark/mobility.meran.eu
- [ ] https://mobility.bz.it/ - we will connect this domain to the new OTP application (I will manage this OpenMove so to have a similar rule as for mobility.meran.eu)
- [ ] http://bus.bz.it/ - I suggest here a simple redirect to mobility.bz.it

Please also 
- [ ] check in our list of running applications if we have some applications connected to this environment, I could have missed something... 

Please note that we are probably in the situation to completely switch-off the API v1 of the mobility domain. We should probably internally discuss how to proceed on that. I would suggest to send a communication to all our Data Access customers that at a certain date (TBD) the API v1 won't be available anymore, so they have time to fix this in case they are still using this API. At that day, we then make the switch-off. We also have to align with Martin and Stefano D. so to properly update the documentation.

**Comment by Piiit** [comment]
Archiving
