### ISSUE TITLE
Data not conforming with schema

### ISSUE THREAD

**Issue by bertolla** [noi-techpark/realtimebus-v2#9]
I noticed that the data provided by SASA contain longer Strings than allowed from the existing schema. Has this limit any reason or was it just overthought? So my question is: Do we need to change the schema or must SASA conform with existing ruleset?
```
Error: ERROR:  value too long for type character varying(2)
Mar  2 10:36:31 ip-172-31-33-221 realtimebus[29237]:     at module.exports.Client._readError (/home/jenkins/realtimebus-v2/node_modules/pg-native/index.js:80:13)
Mar  2 10:36:31 ip-172-31-33-221 realtimebus[29237]:     at module.exports.Client._read (/home/jenkins/realtimebus-v2/node_modules/pg-native/index.js:121:19)
Mar  2 10:36:31 ip-172-31-33-221 realtimebus[29237]:     at PQ.emit (events.js:321:20)
Mar  2 10:36:31 ip-172-31-33-221 realtimebus[29237]:     at PQ.EventEmitter.emit (domain.js:485:12) {
Mar  2 10:36:31 ip-172-31-33-221 realtimebus[29237]:   severity: 'ERROR',
Mar  2 10:36:31 ip-172-31-33-221 realtimebus[29237]:   sqlState: '22001',
Mar  2 10:36:31 ip-172-31-33-221 realtimebus[29237]:   messagePrimary: 'value too long for type character varying(2)',
Mar  2 10:36:31 ip-172-31-33-221 realtimebus[29237]:   sourceFile: 'varchar.c',
Mar  2 10:36:31 ip-172-31-33-221 realtimebus[29237]:   sourceLine: '624',
Mar  2 10:36:31 ip-172-31-33-221 realtimebus[29237]:   sourceFunction: 'varchar'
Mar  2 10:36:31 ip-172-31-33-221 realtimebus[29237]: }
Mar  2 10:36:31 ip-172-31-33-221 realtimebus[29237]: ERROR: Error inserting trip 1110100007: Error: ERROR:  value too long for type character varying(2)
Mar  2 10:36:31 ip-172-31-33-221 realtimebus[29237]:  (receiver.js:82)

```

**Comment by danielrampanelli** [comment]
If I'm not wrong, this error was thrown during an update of the realtime vehicle positions. Therefore, the transmitted "vehicle code" contains more information than it used to (only 2 characters). Assuming this change was necessary, I would therefore adapt the database schema to an appropriate length.

**Comment by bertolla** [comment]
Before they only used BZ and ME in this column. Now we also get something like "ME/BZ"

**Comment by bertolla** [comment]
the property is 'depot'

**Comment by danielrampanelli** [comment]
> Before they only used BZ and ME in this column. Now we also get something like "ME/BZ"

If this information is no longer related to a single “depot” then maybe it would make sense to drop this information (if it’s not used). Theoretically we already know to which “location” or “depot” the vehicles belong to, because vehicles are related to trips and routes.

**Comment by Piiit** [comment]
Archiving
